<script>

document.observe("dom:loaded", function() {
    $$('.registered-users .buttons-set').first().insert('<div class="fb-login-button" data-width="300" data-max-rows="1" data-size="large" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="true" data-scope="public_profile,email" data-onlogin="fbLoginCallback"></div>');
});

window.fbAsyncInit = function() {
    FB.init({
        appId: '183026215696896',
        status: true,
        xfbml: true,
        version: 'v2.7'
    });
};
function fbLoginCallback() {
    FB.getLoginStatus(function(response) {

        console.log(response);

        FB.api('/me', { fields: 'name, first_name, email, gender' }, function(response2) {
                new Ajax.Request('<?php echo Mage::getUrl('sociallogin/login/check', array('_secure' => true)) ?>', {
                    method: "post",
                    parameters: {
                        name: response2.name,
                        firstName: response2.first_name,
                        email: response2.email,
                        accessToken: response.authResponse.accessToken,
                        userId: response.authResponse.userID,
                        signedRequest: response.authResponse.signedRequest
                    },
                    onComplete: function (data) {
                        window.location = data.responseJSON.redirectUrl;
                    }
                });
            }
        );
    });
}
</script>